# Generated by Django 5.0.1 on 2024-04-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0005_nippomodel_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
